coviguard/urls.py
from django.contrib import admin
from django.urls import path,include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('home/', include('login.urls')),

]

login/urls.py
from django.urls import path
from . import views

app_name="login"
urlpatterns = [

 path('', views.home, name = 'home'),
 path("signup/", views.SignUp.as_view(), name="signup"),
 path("login/", views.SignUp.as_view(), name="login"),
]

circle/models.py
from django.db import models

# Create your models here.

class Circle(models.Model):
    circle_id = models.AutoField(primary_key = True)
    circle_name = models.CharField(max_length = 100)
    admin_username = models.CharField(max_length=100)
    no_of_users = models.IntegerField(default = 0)
    #circle_display_image = models.ImageField(upload_to = 'images/')

class CircleUsers(models.Model):
    class Meta:
        unique_together = (('circle_id', 'user_id'),)
    circle_id = models.ForeignKey(Circle, on_delete = models.CASCADE)
    user_id = models.CharField(max_length = 100)
    username = models.CharField(max_length = 100)
    is_admin = models.BooleanField(default=False)
    is_member = models.BooleanField(default=False)

class CirclePolicies(models.Model):
    circle_id = models.ForeignKey(Circle, on_delete = models.CASCADE)
    policy_id = models.IntegerField(default = 0)

class Policy(models.Model):
    policy_id = models.IntegerField(default = 0, primary_key = True)
    policy_name = models.CharField(max_length = 20)
    policy_desc = models.CharField(max_length = 1000)
    policy_level = models.IntegerField(default = 0)

login/models.py
from django.db import models

# Create your models here.

login/forms.py
#registration form
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.forms.widgets import *

class SignUpForm(UserCreationForm):
    email = forms.EmailField(label = 'Please enter your usual email address.',
        max_length = 55,
        required = True,
        widget = forms.EmailInput)# to add more boostrap features or calss use attrs={'class':'form-control'}
    first_name = forms.CharField(max_length=100,required=True)
    last_name = forms.CharField(max_length=100,required=True)
    phone = forms.CharField(label = 'Please enter your phone number without country code')
    #use pincodes instead of full add ? ref- prof's elderly inclass ref.
    wadd = forms.CharField(label = 'Enter Your Work Address ',max_length=5,required=True)
    #same note as wadd.
    hadd = forms.CharField(label = 'Enter Your Home Address ',max_length=5,required=True)
    #dob = forms.DateField(required=True)
    #better to take bool ? ref - ease of use.
    Vaccinated = forms.BooleanField(label = 'Are you vaccinated ?',required=True)
    #only accepting in year-month-date format rn 2006-10-25
    #Date formats needs to be defined DATE_INPUT_FORMATS = ['%m-%d-%Y'],ours is enforced through the dialog showup.
    dob = forms.DateField(widget=NumberInput(attrs={'type': 'date'}))

    class Meta:
        model = User
        fields = ('username', 'email' ,'first_name', 'last_name', 'password1', 'password2','hadd','wadd','phone',)

circle/views.py
from django.shortcuts import render

# Create your views here.

login/views.py
#users/views.py

from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView
from .forms import SignUpForm

# Create your views here.
def home(request):
    return render(request,"login/home.html")
    '''if request.method == "POST":
        #validated form
        form_class = SignUpForm(request.POST)
        if form.is_valid():
            #save to db
            form.save()
            #log them in
            redirect("login/home.html")
    else:
        form = SignUpForm()
    return render(request,"login/signup.html",{'form':form})'''





class SignUp(CreateView):
    #Added feild and modified UserCreationForm for min login/forms.py
    form_class = SignUpForm
    success_url = reverse_lazy("login")
    template_name = "login/signup.html"

login/templates/login/home.html
{% load crispy_forms_tags %}
<form method="post">{% csrf_token %}
<html>
  <head>
    <style>
     body {
      color: pink;
      text-align: center;
      }
    </style>
  </head>
  <body>
    <h1>Hello, {{ user.emailid|default:'Guest' }}</h1>

    <p> Welcome to the Our site</p>
    <div>
      {% if user.is_authenticated %}
          <a href="{% url 'logout' %}">Logout</a>
      {% else %}
          <a href="{% url 'login:signup' %}">Sign Up</a>
          <a href="{% url 'login' %}">Login</a>
      {% endif %}
  </div>
  </body>
</html>

login/templates/login/signup.html
{% block content %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
<h2>Register</h2>
<style>
/* CSS */
.button-1{
  align-items: center;
  background-color: #0A66C2;
  border: 0;
  border-radius: 100px;
  box-sizing: border-box;
  color: #ffffff;
  cursor: pointer;
  display: inline-flex;
  font-family: -apple-system, system-ui, system-ui, "Segoe UI", Roboto, "Helvetica Neue", "Fira Sans", Ubuntu, Oxygen, "Oxygen Sans", Cantarell, "Droid Sans", "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Lucida Grande", Helvetica, Arial, sans-serif;
  font-size: 16px;
  font-weight: 600;
  justify-content: center;
  line-height:20px;
  max-width: 480px;
  min-height: 40px;
  min-width: 0px;
  overflow: hidden;
  padding: 0px;
  padding-left: 20px;
  padding-right: 20px;
  text-align: center;
  touch-action: manipulation;
  transition: background-color 0.167s cubic-bezier(0.4, 0, 0.2, 1) 0s, box-shadow 0.167s cubic-bezier(0.4, 0, 0.2, 1) 0s, color 0.167s cubic-bezier(0.4, 0, 0.2, 1) 0s;
  user-select: none;
  -webkit-user-select: none;
  vertical-align: middle;
}

.button-1:hover,
.button-1:focus {
  background-color: #16437E;
  color: #ffffff;
}

.button-1:active {
  background: #09223b;
  color: rgb(255, 255, 255, .7);
}

.button-1:disabled {
  cursor: not-allowed;
  background: rgba(0, 0, 0, .08);
  color: rgba(0, 0, 0, .3);
}

</style>

<form action="{% url 'login:home' %}" method="post">
  {% csrf_token %}

    <div class="whatever-class-name">
        Please enter your First Name
        {% render_field form.first_name class="form-control" placeholder="First Name" type="text" %}
      </div>
      <div class="whatever-class-name">
        Please enter your last name
        {% render_field form.last_name type="text" class="form-control" placeholder="Last Name" %}
      </div>
      <div class="whatever-class-name">
         Pick a username
        {% render_field form.username type="text" class="form-control" id="exampleInputUsername" placeholder="Username" %}
      </div>
      <div class="whatever-class-name">
        Pick your Password
        {% render_field form.password1 type="password" class="form-control" id="exampleInputPassword" placeholder="Password" %}
      </div>
      <div class="whatever-class-name">
        Re-enter your chosen Password
        {% render_field form.password2 type="password" class="form-control" id="exampleInputPassword1" placeholder="Confirm Password" %}
      </div>
      <div class="whatever-class-name">
        Please Enter your phone number without country-code or hyphens
        {% render_field form.phone type="phone" %}
      </div>
      <div class="whatever-class-name">
        Enter your Work Address
        {% render_field form.wadd%}
      </div>
      <div class="whatever-class-name">
        Enter your Home Address
        {% render_field form.hadd%}
      </div>
      <div class="whatever-class-name">
        Date of Birth
        {% render_field form.dob%}
      </div>
      <div class="whatever-class-name">
        Are you Vaccinated ?
        {% render_field form.Vaccinated%}
      </div>
    <button class="button-1 ">Submit</button>
</form>


<a href="{% url 'login' %}">Back to login</a>
<a href="{% url 'login' %}">Back to Home</a>
{% endblock %}